hosts:
  - rpi1:
      os: raspian
      type: Raspberry PI
      location: garage
  - rpi2:
      os: raspian
      type: Raspberry PI
      location: garage
  - bbone:
      os: ubuntu server(?)
      type: Beagal Board Black
      location: garage
  - mini:
      category: computer
      os: macos
      location: home office
  - macair:
      categories: [ computer, laptop ]
      os: macos
      location: mobile
  - macbook:
      categories: [ computer, laptop ]
      os: macos
      location: mobile
  - gtv:
      category: tv
      location: garage
      brand: visio
  - mstv:
      category: tv
      location: master bedroom
  - lrtv:
      category: tv
      location: living room
  - tp-link:
      os: Todo Figure this one out
      ipaddr: 10.24.0.1
  - zwx:
      description: Zodiac Wireless SDN
      os: OpenWRT
  - zfx:
      description: Zodiac Desktop Switch SDN
      os: OpenWRT
  - zsx:
      description: Zodiac SDN prototype switch
  - iphone7:
      description: Henrys old broken phone
  - samsungX:
      description: Kellys phone
  - samsung Galaxy S6:
      description: Beveled piece of shit phone
  - denon:
      description: Denon 2806ci & Surround Speakers

